### ISSUE TITLE
ship info next version TODO

### ISSUE THREAD

**Issue by KagamiChan** [poooi/plugin-ship-info#73]
- [x] context-menu click support for ship super type button, to choose only ships of this super type
- [ ] in fleet filter -> multiple checkboxes for each fleet
- [x] filter setting saving & loading, only several, e.g. 5 settings can be saved
- [x] improve fleet id style, maybe use SVG instead
