### ISSUE TITLE
ship info 3.x roadmap

### ISSUE THREAD

**Issue by KagamiChan** [poooi/plugin-ship-info#74]
## 3.0
remaining things:
- [x] sally area tag
- [x] center info table
- [x] force update when setting changes / loading bookmarks
- [x] in dock indicator
- [ ] check #73 

## 3.1
- allow choosing columns to show, with presets (similar to ship type filter)
-ship information exporting (csv / json)
